Web1/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required
from django.views.generic import TemplateView, ListView
from django.views.generic.edit import CreateView
from app.principal.views import registerPage, login, update, create, read, delete, index, index1, read_user, delete_user, update_user, logout

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('about/', login_required(TemplateView.as_view(template_name="secret.html"))),
    path('', index.as_view(), name="index"),
    path('index/', index1.as_view(), name="index1"),
    path('register/', registerPage, name="register"),
    path('login/', login, name="login" ),
    path('actualizar/<int:id>', update),
    path('actualizar_user/<int:id>', update_user),
    path('perfil/', create.as_view(),name="perfil"),
    path('read/', read, name="read"),
    path('read_user/', read_user),
    path('delete/<int:id>', delete),
    path('delete_user/<int:id>', delete_user, name="delete_user"),
    path('logout/', logout, name="logout"),
    
]

app/principal/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Perfil(models.Model):
    Ci = models.CharField(max_length=16, null=False, unique=True,error_messages={'required': 'Your C.I. is Required'})
    Nombre = models.CharField(max_length=128, null=False,  error_messages={'required': 'Your Name is Required'}  )
    Apellido = models.CharField(max_length=128, null=False,  error_messages={'required': 'Your Apellido is Required'})
    Correo = models.CharField(max_length=256, null=False,error_messages={'required': 'Your Email is Required'})
    Celular = models.CharField(max_length=16, null=True)
    Whatsapp = models.CharField(max_length=16, null=True)
    Imagen = models.ImageField('Label', upload_to='static/profiles', null=True, blank=True )
    Usuario = models.OneToOneField(User, on_delete=models.CASCADE, null= True, blank=True)

    class meta:

        db_table ="perfil"

app/principal/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

from .models import Perfil


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2'] 

class Perfilform(forms.ModelForm):
    class Meta:
        model = Perfil
        fields = ['Ci','Nombre','Apellido','Correo','Celular','Whatsapp','Imagen']

app/principal/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.forms import inlineformset_factory

from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect
from .forms import CreateUserForm, Perfilform
from django.contrib import messages
from .models import Perfil
from .models import User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login as do_login, logout
from django.contrib.auth.decorators import login_required

from django.views.generic import TemplateView, UpdateView, CreateView, ListView, RedirectView
from django.views.generic.edit import FormView, CreateView, DeleteView

from django.utils.decorators import method_decorator
from django.urls import reverse_lazy, reverse

# Create your views here.

def registerPage(request):
    form = CreateUserForm()
    if request.method =="POST":
        form = CreateUserForm (request.POST)
        if form.is_valid():
            form.save()
        else:
            print(form)    
            return redirect('index')
    else:
        messages.info(request, 'nombre, email o password incorecto')        
    return render (request, "principal/register.html", {'form':form})

@method_decorator(login_required, name='dispatch')
class index(TemplateView):
   template_name = 'principal/index.html'
class index1(TemplateView):
   template_name = 'principal/index1.html'

    
class create(CreateView):
     model = Perfil
     form_class = Perfilform
     template_name = 'principal/perfil.html'
     success_url = reverse_lazy('index')
     def form_valid(self, form):
        form.instance.created_by_user = self.request.user
        return super(create, self).form_valid(form) 
     def form_invalid(self, form):
        print(form)

#def create(request):
 #   form = Perfilform()
  #  if request.method =="POST":
   #     form = Perfilform (request.POST)
    #
     #   if form.is_valid():
      #      form.save()
       #     return HttpResponseRedirect('../login')    
     #       print(form)
    #return render(request,"principal/perfil.html", {"form":form})

def login(request):
    form =AuthenticationForm() 
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']   
            password = form.cleaned_data['password']
            user =authenticate( username=username, password=password)   
            if user is not None:
                do_login(request, user) 
                return redirect('index')
            else:
                messages.info(request, 'Nombre de Usuario o password incorrecto ')
        else:
              messages.info(request, 'invalido nombre de ususario o contraseña  ')            

    return render(request, "principal/login.html", {'form':form})

def logout(request):
    logout(request)
    return redirect('login')

#class read(ListView):
 #   model = Perfilform
  #  template_name = 'principal/read.html'

def read(request):
       perfil = Perfil.objects.all()
       return render(request, "principal/read.html",{'perfil':perfil})

def read_user(request):
    user = User.objects.all()
    print(user)
    return render(request, "principal/read_user.html",{'user':user})    

def update(request, id):
    perfil = Perfil.objects.get(id=id)
    form = Perfilform(request.POST, instance=perfil)
    if form.is_valid():
        form.save()
        return redirect("/read")
    else: 
        messages.info(request, 'error de datos')    
    return render(request,"principal/update.html", {'perfil':perfil})

def update_user(request, id):    
    user = User.objects.get(id=id)
    form = CreateUserForm(request.POST, instance=user)
    if form.is_valid():
        form.save()
        return redirect("/read_user")
    else:
        messages.info(request, 'Error de  DAtos')    
    return render(request, "principal/update_user.html", {'form':form})
    
def delete(request, id):
    perfil = Perfil.objects.get(id=id)
    perfil.delete()
    return redirect("/read")

def delete_user(request, id):
    user = User.objects.get(id=id)
    user.delete()
    return redirect("/read_user")

app/principal/templates/principal/create.html
{% load static %}
<!DOCTYPE html>
<html >
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'principal/images/favicon.png' %}">
        <title>{% block title%} Registrarse{% endblock%}</title>

        <link href="{% static 'principal/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'principal/css/style.css' %}" rel="stylesheet">
        <link href="{% static 'principal/css/blue.css' %}" id="theme" rel="stylesheet">
    </head>

    <body>
        <section id="wrapper">
            <div class="login-register" style="background-image:url({% static 'principal/images/login-register.jpg' %});">        
                <div class="login-box card">
                <div class="card-body "  >
                    
                   {% block content %} 
       
       
                    {% endblock %}
                    
                </div>
              </div>
            </div>
            
        </section>
        
    </body>

</html>

app/principal/templates/principal/index.html
<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="refresh" content="0;url=index">
    <title>SB Admin</title>
    <script language="javascript">
        window.location.href = "index"
    </script>
</head>

<body>
    Go to <a href="index">/dist/index.html</a>
</body>

</html>

app/principal/templates/principal/index1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %} Pagina principal {% endblock %}</title> 
        <link href="{% static 'principal/css/styles.css' %}" rel="stylesheet" />
        <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" crossorigin="anonymous"></script>
     
    </head>
    
    <body class="sb-nav-fixed">
        
        <div class="img2" style="background-image:url({% static 'principal/images/img2.jpg' %});" >
            <div class=""> 
                <div class="card-body ">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark" >
            <a class="navbar-brand" href="../index">Start</a>
            <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars" ></i></button>
            <!-- Navbar Search-->
        
            <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0" >
                <div class="input-group">
                    <input class="form-control" type="text" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" />
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
                    </div>
                </div>
            </form>
        
            <!-- Navbar-->
            <ul class="navbar-nav ml-auto ml-md-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                        <a class="dropdown-item" href="#">Settings</a>
                        <a class="dropdown-item" href="#">Activity Log</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="../login">Logout</a>
                    </div>
                </li>
            </ul>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <a class="nav-link" href="index.html">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Home
                            </a>
                            
                            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                                <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                Layouts
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" href="layout-static.html">Static Navigation</a>
                                    <a class="nav-link" href="layout-sidenav-light.html">Light Sidenav</a>
                                </nav>
                            </div>
                            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                                <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                                Pages
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                        Authentication
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">
                                            <a class="nav-link" href="../login">Login</a>
                                            <a class="nav-link" href="../perfil">Registrar Perfil</a>
                                            <a class="nav-link" href="../read_user">Datos de Usuario</a>
                                            <a class="nav-link" href="../read">Datos perfil</a>
                                            <a class="nav-link" href="../password.html">Forgot Password</a>
                                        </nav>
                                    </div>
                                                                    </nav>
                            </div>
                            
                        </div>
                    </div>
                    <div class="sb-sidenav-footer">
                        <div class="small">Logged in as:</div>
                        Start Bootstrap
                    </div>
                </nav>
            </div>
            <div id="layoutSidenav_content"></div>
                <main>
                    <div class="container-fluid">
                        <div class="login-register" style="background-image:url(images/login-register.jpg);"></div>
                        {% block content %}<br><br><br>  
                        <h1 class="mt-4" style="background-color: cornflowerblue; color: cornsilk; text-align: center;"> <em> BIENVENIDO A MI PAGINA </em></h1>
                        {% endblock %}
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'principal/js/scripts.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="assets/demo/chart-area-demo.js"></script>
        <script src="assets/demo/chart-bar-demo.js"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
        <script src="assets/demo/datatables-demo.js"></script>
     </div>
    </div>
</div>
    </body>
</html>

app/principal/templates/principal/login.html
{% extends "principal/create.html" %}

{% block title  %} login {% endblock %}

{% block h3  %} LOGIN {% endblock %}
<br><br><br>

{%block content%}
<form method="POST" action="">
    {% csrf_token%}

<h3 class="box-title m-b-20" >  <em>LOGIN</em> </h3> 
<div class="form-group">
    <div class="col-xs-12">
        <input class="form-control" type="text" required="" placeholder="Nombre de Usuario" name="username">
    </div>
</div>
<div class="form-group">
    <div class="col-xs-12">
        <input class="form-control" type="password" required="" placeholder="Passsword" name="password">
    </div>
</div>
<div class="ml-auto">
    <a href="javascript:void(0)" id="to-recover" class="text-muted"><i class="fa fa-lock m-r-5"></i> Forgot pwd?</a> 
</div>
<div class="form-group text-center m-t-20">
    <div class="col-xs-12">
        <button class="btn btn-info btn-lg btn-block text-uppercase waves-effect waves-light" type="submit">LOG IN</button>
    </div>
</div>
{% for message in messages %}
<p id="messages">{{message}}</p>
{% endfor%}
<div class="form-group m-b-0">
    <div class="col-sm-12 text-center">
        Already have an account? <a href="../register" class="text-info m-l-5"><b>Sign up</b></a>
    </div>
</div>
</form>
{% endblock %}

app/principal/templates/principal/perfil.html
{% extends  "principal/index1.html" %}

{% block title %}Info perfil {% endblock %}

{% block content  %}

<form method="POST" > 
    <br><br><br>
    {%  csrf_token %}
    <h3 class="box-title m-b-20" style="text-align: center; color: rgb(19, 34, 34);" >  <em> Crear Perfil </em> </h3> 

    <div class="form-group ">
        <div class="col-xs-12">
            {{form.Ci}}
        </div>
    </div>    

<div class="form-group ">
    <div class="col-xs-12">
        {{form.Nombre}}
    </div>
</div>
<div class="form-group ">
    <div class="col-xs-12">
        {{form.Apellido}}
    </div>
</div>
<div class="form-group ">
    <div class="col-xs-12">
        {{form.Correo}}
    </div>
</div>
<div class="form-group ">
    <div class="col-xs-12">
        {{form.Celular}}
    </div>
</div>
<div class="form-group ">
    <div class="col-xs-12">
        {{form.Whatsapp}}
    </div>
</div>
<div class="form-group ">
    <div class="col-xs-12">
        {{form.Imagen}}
    </div>
</div>
    
    <button class="btn btn-info btn-lg btn-block text-uppercase waves-effect waves-light" type="submit" name= "Create User">Sign Up</button>
    <div class="form-group m-b-0">
        <div class="col-sm-12 text-center">
            Already have an account? <a href="login" class="text-info m-l-5"><b>Sign In</b></a>
        </div>
    </div>
    <script>
        var form_fields = document.getElementsByTagName('input')

        form_fields[1].placeholder='';
        form_fields[2].placeholder='Introdusca su C.I.';
        form_fields[3].placeholder='Introdusca su Nombre';
        form_fields[4].placeholder='Introdusca su Apellido';
        form_fields[5].placeholder='Introdusca su Correo';
        form_fields[6].placeholder='Introdusca su Celular';
        form_fields[7].placeholder='Introdusca su Whatsapp';
        for (var field in form_fields){
            form_fields[field].className += ' form-control'
        }
    </script>


{% endblock %}

app/principal/templates/principal/read.html
{% extends "principal/index1.html" %}

{% block title %} Informacion {% endblock %}

{% block content %}
 <body>  
    <form class="table table-striped table-bordered table-sm" > 
<table class="table table-striped table-bordered table-sm" align="center">  
    <thead class="thead-dark">  
        <h4>Informacion de perfil</h4>
    <tr>  
        <th> CI</th>  
        <th> NOMBRE</th>  
        <th> APELLIDO</th>  
        <th> EMAIL</th>  
        <th> CELULAR</th>  
        <th> WHATSAPP</th>  
        <th> IMAGEN</th>  
        <th>ACTUALIZAR</th>  
        <th>BORRAR</th>
    </tr>  
    </thead>  
    <tbody>  
{% for perfil in perfil %}  
    <tr>  
        <td>{{ perfil.Ci }}</td>  
        <td>{{ perfil.Nombre }}</td>  
        <td>{{ perfil.Apellido }}</td>  
        <td>{{ perfil.Correo }}</td>  
        <td>{{ perfil.Celular }}</td>  
        <td>{{ perfil.Whatsapp }}</td>  
        <td>{{ perfil.Imagen }}</td>  
        <td><a href="/actualizar/{{ perfil.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a></td>  
        <td><a href="/delete/{{ perfil.id }}">Delete</a></td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="/read" class="btn btn-primary">Add New Record</a></center>  
</form>
</body>  

{% endblock %}

app/principal/templates/principal/read_user.html
{% extends  "principal/index1.html" %}

{% block title %}Datos Usuario {% endblock %}
{% block content  %}
<body>  
    <form class="table table-striped table-bordered table-sm" method="GET" > 
<table class="table table-striped table-bordered table-sm"  >  
    <thead class="thead-dark">  
        <h4>Informacion de usuario</h4>
    <tr>  
        <th> USERNAME</th>  
        <th> EMAIL</th>  
        <th> PASSWPRD</th>
         <th>Actualizar</th>
         <th>Eliminar</th>
    </tr>  
    </thead>  
    <tbody>  
{% for user in user %}  
    <tr>  
        <td>{{ user.username }}</td>  
        <td>{{ user.email }}</td>  
        <td> {{user.password}}</td>  
        <td><a href="/actualizar_user/{{ user.id }}"><span class="glyphicon glyphicon-pencil" >Editar</span></a></td>  
        <td><a href="/delete_user/{{ user.id }}">Eliminar</a></td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="/read" class="btn btn-primary">Add New Record</a></center>  
</form>
</body>  




{% endblock %}

app/principal/templates/principal/register.html
{% extends "principal/create.html" %}

{% block title %} Register User {% endblock %}

{% block content %}
<form method="POST"  action="" >
    {% csrf_token%}
    <h3 class="box-title m-b-20">Sign Up</h3>
    <div class="form-group">
        <div class="col-xs-12">
          {{form.username}}
        </div>
    </div>
    <div class="form-group ">
        <div class="col-xs-12">
          {{form.email}}
        </div>
    </div>
   
    <div class="form-group ">
        <div class="col-xs-12">
        {{form.password1}}
        </div>
    </div>
    <div class="form-group">
        <div class="col-xs-12">
            {{form.password2}}
        </div>
    </div>
    <div class="form-group text-center m-t-20">
        <div class="col-xs-12">
            <button class="btn btn-info btn-lg btn-block text-uppercase waves-effect waves-light" type="submit" name= "Create User">Sign Up</button>
        </div>
    </div>
    <div class="form-group m-b-0">
        <div class="col-sm-12 text-center">
            Already have an account? <a href="../login" class="text-info m-l-5"><b>Sign In</b></a>
        </div>
    </div>
    <script>
        var form_fields = document.getElementsByTagName('input')
        form_fields[1].placeholder='Nombre de Usuario...';
        form_fields[2].placeholder='Email...';
        form_fields[3].placeholder='Password...';
        form_fields[4].placeholder='confirmar Password...';
        for (var field in form_fields){
            form_fields[field].className += ' form-control'
        }
    </script>
</form> 
</form>






{% endblock %}

app/principal/templates/principal/update.html
{% extends  "principal/index1.html" %}

{% block title %}Actualizar perfil {% endblock %}

{% block content  %}
<form method="POST" action="">  
    {% csrf_token %}  
<div class="container">  
<br>  
<div class="form-group row">  
<label class="col-sm-1 col-form-label"></label>  
<div class="col-sm-4">  
<h3>Update Perfil</h3>  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label"> Ci:</label>  
<div class="col-sm-4">  
    <input type="text" name="Ci" id="id_Ci" required  value="{{ perfil.Ci }}"/>  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Nombre:</label>  
<div class="col-sm-4">  
    <input type="text" name="Nombre" id="id_Nombre" required  value="{{ perfil.Nombre }}" />  
</div>  
</div>  
<div class="form-group row">  
    <label class="col-sm-2 col-form-label">Apellido:</label>  
    <div class="col-sm-4">  
        <input type="text" name="Apellido" id="id_Apellido" required  value="{{ perfil.Apellido }}" />  
    </div>  
    </div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Email:</label>  
<div class="col-sm-4">  
    <input type="email" name="Correo" id="id_Correo" required  value="{{ perfil.Correo }}" />  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Celular:</label>  
<div class="col-sm-4">  
    <input type="number" name="Celular" id="id_Celular"  value="{{ perfil.Celular }}" />  
</div>  
</div>  
<div class="form-group row">  
    <label class="col-sm-2 col-form-label">Whatsapp:</label>  
    <div class="col-sm-4">  
        <input type="number" name="Whatsapp" id="id_Whatsapp" value="{{ perfil.Whatsapp }}" />  
    </div>  
    </div>  
    <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Imagen:</label>  
        <div class="col-sm-4">  
            <input type="image" name="Imagen" id="id_Imagen"  value="{{ perfil.Imagen }}" />  
        </div>  
        </div>      
<div class="form-group row">  
<label class="col-sm-1 col-form-label"></label>  
<div class="col-sm-4">  
<button type="submit" class="btn btn-success">Update</button>  
</div>  
</div>  
</div>  
</form>  


{% endblock %}

app/principal/templates/principal/update_user.html
{% extends  "principal/index1.html" %}

{% block title %}Actualizar User {% endblock %}

{% block content  %}
<br><br><br>
<form method="POST">
<p>
    <label  > Username: </label>
    <input type="text" name="username" required id="id_usernama" value="{{form.username}}"> 
</p>
<p>
    <label for="id_email"> Email:</label> 
    <input type="text" name="email" maxlength="254"  id="id_email" value="{{form.email}}" >
</p>
<p>
    <label for="id_passwor1"> password</label>
    <input type="password" name="password1" required id="password1" value="{{form.password1}}">
</p>
<p>
    <label for="id_password2"> password confirme</label>
    <input type="password" name="password2" requiredq id="password2"  value="{{form.password2}}"> 
</p>
</form>
{% endblock %}